name: deploy-collaboration

on:
  push:
    branches:
      - master
    paths:
      - 'packages/calendar/collaboration/**'
  workflow_dispatch:

env:
  AUTO_DEPLOY: ${{ vars.AUTO_DEPLOY }}

defaults:
  run:
    working-directory: packages/calendar/collaboration

jobs:
  build:
    name: Build Contact Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

  deploy:
    name: Deploy to AWS (manual only)
    needs: build
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push' && vars.AUTO_DEPLOY == 'true')
      ||
      github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies & build
        run: |
          npm install
          npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - name: Configure AWS CLI
        uses: shinyinc/action-aws-cli@v1.2

      - name: Sync to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/calendar/collaboration/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} \
            --paths "/calendar/collaboration/latest/remoteEntry.js"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
